name: scribbly
description: crowdsharing ideas

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_staggered_grid_view: ^0.6.1
  font_awesome_flutter: ^10.1.0
  get: ^4.6.5
  http: ^0.13.4
  loading_animation_widget: ^1.2.0+2
  modal_bottom_sheet: ^2.1.0

dev_dependencies:
  change_app_package_name: ^1.0.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/profile/
    - assets/splash/

  fonts:
    - family: Emporia
      fonts:
        - asset: assets/fonts/EmporiaRegular.otf
    - family: Sebino
      fonts:
        - asset: assets/fonts/Sebino-Bold.ttf
    - family: Astra
      fonts:
        - asset: assets/fonts/astra.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/RobotoMono-Regular.ttf
        - asset: assets/fonts/RobotoMono-Bold.ttf
    - family: Playfair
      fonts:
        - asset: assets/fonts/PlayfairDisplay-Regular.ttf
        - asset: assets/fonts/PlayfairDisplay-Bold.ttf
    - family: Blanco
      fonts:
        - asset: assets/fonts/Blanco-Bold.ttf
    - family: Helvetica
      fonts:
        - asset: assets/fonts/HelveticaNeueBd.ttf
    - family: Sailor
      fonts:
        - asset: assets/fonts/SAILORRegular.ttf
        - asset: assets/fonts/SAILORBold.ttf
    - family: Proxima
      fonts:
        - asset: assets/fonts/ProximaNova-Regular.otf
        - asset: assets/fonts/ProximaNova-Bold.otf
        - asset: assets/fonts/ProximaNova-Extrabold.otf
    - family: Paul
      fonts:
        - asset: assets/fonts/PaulGrotesk-Bold-Trail.otf
